Create mainRouter
MarcosRodriguezAlonso/the-why-blog pull request #27
Opened 2024-05-18 16:13 UTC by ErLlu

He creado un mainRouter, también, he añadido tambien un outet en app.tsx, he cambiado también los paths de NavegationMenu, y por último he añadido los componentes para las páginas: AddPostPage, PostListPage y NotFoundPage. También he añadido react-dom y react-router-dom.

2024-05-18 17:26 UTC, sayloryna requested changes

2024-05-18 17:26 UTC, sayloryna commented on src/components/NavigationMenu/NavigationMenu.test.tsx
> +          <NavigationMenu />
ala, que hace esto?

2024-05-18 17:26 UTC, sayloryna commented on src/components/PostCard/PostCard.test.tsx
>      test("Then it should show a date with '3/5/2024'", () => {
este texto esta mal When it receives a post with the date: '3/5/2024'"

2024-05-18 17:26 UTC, sayloryna commented on src/pages/NotFoundPage/NotFoundPage.tsx
> +  return <p>Error: Page not found</p>;
esto mejor un h2 creo

2024-05-18 17:31 UTC, ErLlu commented on src/pages/NotFoundPage/NotFoundPage.tsx
> +  return <p>Error: Page not found</p>;
pues te tengo que dar la razón

2024-05-18 17:32 UTC, sayloryna approved these changes

2024-05-18 17:33 UTC, ErLlu commented on src/components/PostCard/PostCard.test.tsx
>      test("Then it should show a date with '3/5/2024'", () => {
ya estaba el cambio hecho, pero un merge lo jodió

2024-05-18 17:34 UTC, ErLlu commented on src/components/NavigationMenu/NavigationMenu.test.tsx
> +          <NavigationMenu />
el lunes os comento

2024-05-18 17:36 UTC, merged

2024-05-18 17:40 UTC, ErLlu commented on src/components/NavigationMenu/NavigationMenu.test.tsx
> +          <NavigationMenu />
nah, te cuento por aquí, he creado un mock que renderiza el componente NavigationMenu dentro de MemoryRouter. Lo que simula un router falso para el test para que no nos dé el error que vimos el viernes de "cannot destructure property 'future'..."

2024-05-18 20:00 UTC, the-refactor-project commented
Esta PR tiene un commit con muchas cosas. No podemos meter varios componentes ni varias páginas en un solo commit.

2024-05-19 17:08 UTC, ErLlu commented
> Esta PR tiene un commit con muchas cosas. No podemos meter varios componentes ni varias páginas en un solo commit.

´vale, tomo nota

2024-05-19 17:21 UTC, sayloryna commented on src/components/NavigationMenu/NavigationMenu.test.tsx
> +          <NavigationMenu />
aah noice

2024-05-19 17:21 UTC, sayloryna commented on src/components/PostCard/PostCard.test.tsx
>      test("Then it should show a date with '3/5/2024'", () => {
sad